faztcommunity/fazt-api

README.md
=> add new branch dev

src/controllers/project.controller.ts
=> [Feat] Delete Projects Changing Status

src/models/Jobs.ts, src/models/Misc.ts, src/models/Suggestions.ts, src/models/Workshops.ts
Add the workshop schema and others, which are in process.
=> add worshop schema and others

src/routes/jobs.routes.ts
Documentation jobs.routes.js complete
=> feat: documentation jobs.routes

src/routes/jobs.routes.ts, src/routes/projects.routes.ts
=> Documentation  updated

src/routes/jobs.routes.ts, src/routes/projects.routes.ts, src/routes/tasks.routes.ts
Documentation tasks.routes complete
=> Documentation complete

src/routes/jobs.routes.ts
update documentation jobs.routes
=> Documentation update

src/app.ts, src/controllers/workshop.controller.ts, src/models/Discord.ts, src/models/Jobs.ts, src/models/Task.ts, src/routes/discord.routes.ts, src/routes/jobs.routes.ts, src/routes/misc.routes.ts, src/routes/tasks.routes.ts, src/routes/users.routes.ts, src/utils/auth.ts
Added middleware error 404 not found.
=> fix(middleware): added middleware error

src/@types/enums.d.ts, src/@types/index.d.ts, src/config/redis.ts, src/middlewares/redis.middleware.ts, src/validators/discord.validator.ts, src/validators/jobs.validator.ts, src/validators/users.validator.ts
fixed error in development don't found the ERouter enum
=> Fix: routes enum

src/controllers/jobs.controller.ts, src/controllers/project.controller.ts, src/controllers/task.controllers.ts, src/controllers/user.controller.ts, src/controllers/workshop.controller.ts, src/middlewares/redis.middleware.ts, src/models/Project.ts, src/scripts/data/project.json, src/utils/pages.ts
- created pagination in the get all routes controllers using query `page` & `limit`
- changed format for `response`
- added get all `projects` by `tags` in the url query
- changed `githubURL` to `github_url` in the project model
- changed `projectType` to `type` in the project model
- `tasks`
- `projects`
- `users`
- `jobs`
- `workshops`
=> feat: pagination, format for responses and get projects by query tags

__tests__/routes/user.route.test.ts, __tests__/utils/dbHandler.ts, __tests__/utils/server.ts, package-lock.json, package.json, tsconfig.json
- Added jest supertest and mongodb-memory-server libraries
- Added `__tests__` folder
- Added utils for testing
- Modified package.json and included jest config
- Added jest and supertest types
=> refactor(tests): added libraries for testing and configuration

src/controllers/misc.controller.ts, src/controllers/new.controller.ts, src/routes/index.ts, src/routes/new.routes.ts
Add controller (news), route and insert route in index.ts
=> feat(controller): add controllers and route

__tests__/routes/jobs.router.test.ts, __tests__/routes/project.router.test.ts, __tests__/routes/task.route.test.ts, __tests__/utils/dbHandler.ts, __tests__/utils/server.ts
- Added a couple of lines in clearDatabase () (
- I tested projects, discord, misc, jobs and tasks tests 
- Error in discord and misc
See if it is correct because I have warnings of deprecated.
=> fix(test): add projects, discord, misc, jobs and tasks tests

README.md, package.json, src/controllers/discord.controller.ts, src/controllers/misc.controller.ts, src/routes/github.routes.ts, src/routes/index.ts, src/routes/news.routes.ts, src/routes/users.routes.ts, src/swagger.json, src/swagger.yaml
-  Created the basic documentation of all the endpoints in the project up until now.
-  Refactored misc and discord endpoints to send the response in the correct format.
=> refactor(documentation): migrated docs from openapi 2.0 to openapi 3.0.1

__tests__/routes/tasks.routes.test.ts, __tests__/utils/tasks.ts, package-lock.json, package.json
Added tasks testing: 
- get
- get/id
- post
- put 
- delete
=> feat: added tasks testing

src/entities/Skill.ts, src/entities/SkillUser.ts, src/entities/User.ts, tsconfig.json
add skill, skill_user and user entities.
=> fix(entitie): add skill, skill_user and user entities

src/entities/rol-user.entity.ts, src/entities/rol.entity.ts, src/entities/social-media-user.entity.ts, src/entities/social-media.entity.ts, src/entities/user.entity.ts
Change of references in RolUserEntity and RolEntity.
Added new entities (SocialMediaEntity and SocialMediaUserEntity)
Added relations in UserEntity
=> feat(entities): added new entities

src/entities/team.entity.ts
* add @Column()
* add @Index()
* add all team.entity.ts
=> feat(entity): entityTeam

src/entities/skill-category.entity.ts, src/entities/skill.entity.ts, src/entities/team.entity.ts
- New entity skill-category.entity added
- Relation to SkillCategoryEntity added in SkillEntity
=> feat(entities): skill category entity added

src/entities/category-project.entity.ts, src/entities/category.entity.ts, src/entities/skill-category.entity.ts, src/entities/skill.entity.ts
- New entity category.entity added
- Relation to CategoryEntity added in SkillCategoryEntity
- New entity category-project.entity added
- Relation to CategoryProjectEntity added in CategoryEntity
- Relations with category project and skill category fixed
=> feat(entities): category and category-project entities added

src/common/enumerations/state.ts, src/controllers/project.controller.ts, src/routes/project.route.ts, src/services/project.service.ts
Files added:
project.service.ts
project.controller.ts
project.route.ts
And enum:
StatusProject enum added in common/enumerations/state.ts
=> chore: project endpoints added

src/controllers/project.controller.ts, src/services/project.service.ts
projects endpoints fixed
tested
=> chore: projects endpoints fixed

src/controllers/project-user.controller.ts, src/controllers/rol-user.controller.ts, src/controllers/skill-user.controller.ts, src/controllers/social-media-user.controller.ts, src/routes/index.ts, src/routes/project-user.routes.ts, src/services/project-user.service.ts
projectUser endpoints added
fix indes.ts in Routes respecting hierarchy.
=> chore: add project user endpoints fix routes/index

src/controllers/category-project.controller.ts, src/controllers/project-team.controller.ts, src/controllers/skill-category.controller.ts, src/controllers/skill-project.controller.ts, src/controllers/skill-user.controller.ts, src/entities/rol-user.entity.ts, src/routes/category.routes.ts, src/routes/index.ts, src/routes/project-team.routes.ts, src/services/category.service.ts, src/services/rol-user.service.ts, src/services/skill-category.service.ts, src/services/skill.service.ts, src/services/social-media-user.service.ts, src/services/social-media.service.ts, src/services/team.service.ts
First refactor 
-fix endpoints names
-rename variables
-fix endpoints errors
=> refactor: first refactor fix endpoints

src/config/swagger.ts, src/controllers/project-category.controller.ts, src/controllers/team-project-user.controller.ts, src/entities/category.entity.ts, src/entities/project-category.entity.ts, src/entities/project-team.entity.ts, src/entities/project-user.entity.ts, src/entities/project.entity.ts, src/entities/team-project-user.entity.ts, src/entities/team.entity.ts, src/routes/index.ts, src/routes/project-category.routes.ts, src/routes/team-project-user.routes.ts, src/services/project-category.service.ts, src/services/project-user.service.ts, src/services/team-project-user.service.ts
Refactor:
project-category
add:
team project user
fixed another endpoint
=> refactor: refactor endpoints add new endpoint

src/controllers/team-project-user.controller.ts, src/entities/project-category.entity.ts, src/entities/team-project-user.entity.ts, src/routes/index.ts, src/routes/team-project-user.routes.ts, src/services/team-project-user.service.ts
Fix contrains errors
Clean conflicts
=> fix: conflicts name contrains
